### ISSUE TITLE
Error loading QML file

### ISSUE THREAD

**Issue by sundarv85** [wojnilowicz/workrave-applet#5]
I installed this applet and I'm getting this error

> Error loading QML file: file:///home/sundarv/.local/share/plasma/plasmoids/org.kde.workraveApplet/contents/ui/main.qml:103:16: Expected token ';'

Any idea what the issue could be?

**Comment by wojnilowicz** [comment]
No idea. First, you seem to be using 0.1 version, and the latest one is 0.2. Second, maybe your interpreter doesn't handle "let" keyword, so try changing
"for (let i = 0; i < timersModel.count; ++i)"
to 
"for (var i = 0; i < timersModel.count; ++i)"
in
file:///home/sundarv/.local/share/plasma/plasmoids/org.kde.workraveApplet/contents/ui/main.qml

Besides, what's your OS, Qt and KDE Plasma version?

**Comment by sundarv85** [comment]
Hi @wojnilowicz 

I'm using 0.2 - I tried both from the KDE store and directly from Git.

WRT the other details:

![image](https://user-images.githubusercontent.com/11090193/110451416-77653980-80c4-11eb-8883-c1076949dbc1.png)

**Comment by wojnilowicz** [comment]
Your Qt version is 5.11.3, and the code uses "let" keyword that appeared only from Qt 5.12, so it's not backward compatible. You can open "file:///home/sundarv/.local/share/plasma/plasmoids/org.kde.workraveApplet/contents/ui/main.qml" and replace all "let" keywords with "var" keywords, and see if it works for you.

**Comment by wojnilowicz** [comment]
I ported my applet to Plasma 6 and not planning to work on the Plasma 5 version of it.
